"model":
  "type": "DFNet"
  "params":
    "in_channels": 4
    "hidden_channels": 64
    "L": 5
    "k": 12

"optimizer":
  "type": "AdamW"
  "params":
    "lr": 0.001

"lr_scheduler":
  "type": "MultiStepLR"
  "params":
    "milestones": [10, 25]
    "gamma": 0.2

"dataset":
  "data_dir": "data"
  "use_augmentation": True
  "rgb_augmentation_probability": 0.8

"trainer":
  "batch_size": 4
  "test_batch_size": 1
  "multigpu": True
  "num_workers": 16
  "shuffle": True
  "max_epoch": 40
  "loss_type": "custom_masked_mse_loss"

"stats":
  "stats_dir": "stats"
  "stats_exper": "default"
