"model":
  "type": "DFNet"
  "params":
    "in_channels": 4
    "hidden_channels": 64
    "L": 5
    "k": 12

"dataset":
  "train":
  "test":
    "type": "cleargrasp"
    "data_dir": "data-cleargrasp"
    "image_size": !!python/tuple [256, 144]
    "use_augmentation": False

"dataloader":
  "num_workers": 16
  "shuffle": True

"trainer":
  "criterion":
    "type": "custom_masked_mse_loss"
    "epsilon": 0.00000001

"metrics":
  "types": ["MSE", "MaskedMSE", "RMSE", "MaskedRMSE", "REL", "MaskedREL", "MAE", "MaskedMAE", "Threshold@1.05", "MaskedThreshold@1.05", "Threshold@1.10", "MaskedThreshold@1.10", "Threshold@1.25", "MaskedThreshold@1.25"]
  "epsilon": 0.00000001

"stats":
  "stats_dir": "stats"
  "stats_exper": "small"
